
# Build a local alice binary using docker.

DOCKER := docker

DOCKER_CONTAINER := alice-lg-build
DOCKER_IMAGE := golang:1.18

all: alice
	cp cmd/alice-lg/alice-lg-* bin/

ui:
	$(MAKE) -C ui/ -f Makefile.docker client_prod

alice: client
	$(MAKE) -C cmd/alice-lg -f Makefile.docker

.PHONY: client alice
