
DOCKER_IMAGE := alice-lg-golang:latest
DOCKER_EXEC := docker run --rm -t -i \
	-v `pwd`/../:/go/src/github.com/alice-lg/alice-lg \
	alice-lg-golang:latest /bin/sh -c 


image:
	docker build . -t alice-lg-golang:latest

dev: 
	$(DOCKER_EXEC) "cd backend && make dev"

prod: image
	$(DOCKER_EXEC) "cd backend && make prod"




