#!/bin/bash

#
# Alice Post Install Hook:
# Create the required user and set permissions
#

SERVICE=alice-lg

echo "[i] Post install $SERVICE"
echo "[i] Creating user and updating permissions"
useradd --system -d /opt/alice-lg/$SERVICE $SERVICE

echo "[i] Fixing permissions"
chown -R $SERVICE:$SERVICE /opt/alice-lg/$SERVICE
